sonar.projectKey=telegraphhillpark_dast_project
sonar.organization=telegraphhillpark

sonar.projectName=DAST Analyzer
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/migrations/**,**/tests/**

# Python coverage
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.11

# TypeScript
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
